language: go
go: 
 - 1.1
 - 1.2
 - 1.3
 - release
 - tip

install:
 - go get github.com/lino-network/goflv_z
 - go get github.com/lino-network/goamf_z
 - go get github.com/lino-network/golog_z

script:
 - go test -v ./...
